"use client";

import { createElement, Fragment, type ReactNode } from "react";
import { cn } from "@/lib/utils";
import type { DOMNode } from "./DOMTree";

// Deliberately small allowlist — every DOMNode in this app is generated by
// our own deterministic step logic (never raw user HTML), so this renders
// real elements directly instead of using dangerouslySetInnerHTML.
const ALLOWED_TAGS = new Set(["div", "p", "span", "a", "mark", "strong", "em", "ul", "li", "br"]);

function renderNode(node: DOMNode): ReactNode {
  if (node.tag === "#text") {
    return node.text;
  }

  const tag = ALLOWED_TAGS.has(node.tag) ? node.tag : "span";
  const props: Record<string, unknown> = { key: node.id };
  if (node.attrs?.href) props.href = node.attrs.href;
  if (node.attrs?.class) props.className = node.attrs.class;

  const children = node.children?.map((child) => renderNode(child));
  return createElement(tag, props, children && children.length > 0 ? children : node.text);
}

export interface BrowserPreviewProps {
  root: DOMNode;
  className?: string;
}

export function BrowserPreview({ root, className }: BrowserPreviewProps) {
  return (
    <div className={cn("rounded-lg border border-border bg-background p-4", className)}>
      <p className="mb-2 text-xs font-medium text-muted-foreground">Browser Preview</p>
      <div className="max-w-none text-sm leading-relaxed text-foreground [&_mark]:rounded [&_mark]:bg-amber-300/60 [&_mark]:px-0.5 dark:[&_mark]:bg-amber-400/30 [&_a]:text-primary [&_a]:underline">
        <Fragment>{renderNode(root)}</Fragment>
      </div>
    </div>
  );
}
